import type { GrowthVerticalId } from "../config/verticals";
import { getVerticalConfig } from "../config/verticals";

export type IndustryMetricDefinition = {
  key: string;
  label: string;
  unit: "currency" | "count" | "percentage" | "ratio" | "score" | "duration";
  direction: "higher_is_better" | "lower_is_better";
  diagnosticRole: "north_star" | "driver" | "guardrail";
};

export type IndustryAdapter = {
  id: GrowthVerticalId;
  label: string;
  primaryGoal: string;
  metrics: readonly IndustryMetricDefinition[];
  growthLevers: readonly string[];
  commonDataSources: readonly string[];
};

const metric = (key: string, label: string, unit: IndustryMetricDefinition["unit"], diagnosticRole: IndustryMetricDefinition["diagnosticRole"], direction: IndustryMetricDefinition["direction"] = "higher_is_better"): IndustryMetricDefinition => ({ key, label, unit, diagnosticRole, direction });

const STANDARD_SOURCES = ["website", "analytics", "crm", "reviews", "transactions", "documents"] as const;

const ADAPTERS: Record<GrowthVerticalId, IndustryAdapter> = {
  restaurant: { id: "restaurant", label: "Restaurants & food service", primaryGoal: getVerticalConfig("restaurant").primaryGoal, metrics: [metric("revenue", "Revenue", "currency", "north_star"), metric("average_ticket", "Average ticket", "currency", "driver"), metric("reservations", "Reservations", "count", "driver"), metric("reviews", "Reviews", "count", "driver"), metric("repeat_customers", "Repeat customers", "count", "driver")], growthLevers: ["demand", "conversion", "average_ticket", "retention", "reputation"], commonDataSources: STANDARD_SOURCES },
  beauty: { id: "beauty", label: "Beauty & aesthetics", primaryGoal: getVerticalConfig("beauty").primaryGoal, metrics: [metric("bookings", "Bookings", "count", "north_star"), metric("rebooking_rate", "Rebooking rate", "percentage", "driver"), metric("retention", "Retention", "percentage", "driver"), metric("average_ticket", "Average ticket", "currency", "driver"), metric("reviews", "Reviews", "count", "guardrail")], growthLevers: ["bookings", "rebooking", "utilization", "service_mix", "reputation"], commonDataSources: STANDARD_SOURCES },
  barber: { id: "barber", label: "Barbershops", primaryGoal: getVerticalConfig("barber").primaryGoal, metrics: [metric("bookings", "Bookings", "count", "north_star"), metric("rebooking_rate", "Rebooking rate", "percentage", "driver"), metric("retention", "Retention", "percentage", "driver"), metric("average_ticket", "Average ticket", "currency", "driver"), metric("reviews", "Reviews", "count", "guardrail")], growthLevers: ["rebooking", "retention", "capacity", "local_visibility"], commonDataSources: STANDARD_SOURCES },
  hairdresser: { id: "hairdresser", label: "Hair salons", primaryGoal: getVerticalConfig("hairdresser").primaryGoal, metrics: [metric("bookings", "Bookings", "count", "north_star"), metric("rebooking_rate", "Rebooking rate", "percentage", "driver"), metric("retention", "Retention", "percentage", "driver"), metric("average_ticket", "Average ticket", "currency", "driver"), metric("reviews", "Reviews", "count", "guardrail")], growthLevers: ["rebooking", "utilization", "service_mix", "retention"], commonDataSources: STANDARD_SOURCES },
  fitness: { id: "fitness", label: "Fitness businesses", primaryGoal: getVerticalConfig("fitness").primaryGoal, metrics: [metric("memberships", "Memberships", "count", "north_star"), metric("retention", "Retention", "percentage", "driver"), metric("attendance", "Attendance", "count", "driver"), metric("leads", "Leads", "count", "driver"), metric("revenue_per_member", "Revenue per member", "currency", "driver")], growthLevers: ["lead_generation", "trial_conversion", "retention", "reactivation", "utilization"], commonDataSources: STANDARD_SOURCES },
  hotel: { id: "hotel", label: "Hotels & hospitality", primaryGoal: getVerticalConfig("hotel").primaryGoal, metrics: [metric("occupancy", "Occupancy", "percentage", "north_star"), metric("adr", "ADR", "currency", "driver"), metric("revpar", "RevPAR", "currency", "driver"), metric("direct_bookings", "Direct bookings", "count", "driver"), metric("reviews", "Reviews", "count", "guardrail")], growthLevers: ["occupancy", "direct_demand", "adr", "upsell", "reputation"], commonDataSources: STANDARD_SOURCES },
  home_services: { id: "home_services", label: "Home & local services", primaryGoal: getVerticalConfig("home_services").primaryGoal, metrics: [metric("qualified_leads", "Qualified leads", "count", "north_star"), metric("quote_rate", "Quote rate", "percentage", "driver"), metric("win_rate", "Win rate", "percentage", "driver"), metric("reviews", "Reviews", "count", "guardrail"), metric("repeat_business", "Repeat business", "count", "driver")], growthLevers: ["lead_quality", "response_speed", "quote_conversion", "reviews", "repeat_business"], commonDataSources: STANDARD_SOURCES },
  construction: { id: "construction", label: "Construction & contractors", primaryGoal: getVerticalConfig("construction").primaryGoal, metrics: [metric("qualified_leads", "Qualified leads", "count", "north_star"), metric("quote_rate", "Quote rate", "percentage", "driver"), metric("win_rate", "Win rate", "percentage", "driver"), metric("project_margin", "Project margin", "percentage", "guardrail"), metric("reviews", "Reviews", "count", "driver")], growthLevers: ["lead_quality", "proposal_conversion", "win_rate", "margin", "reputation"], commonDataSources: STANDARD_SOURCES },
  property_management: { id: "property_management", label: "Property management", primaryGoal: getVerticalConfig("property_management").primaryGoal, metrics: [metric("revenue", "Revenue", "currency", "north_star"), metric("occupancy", "Occupancy", "percentage", "driver"), metric("response_time", "Response time", "duration", "driver", "lower_is_better"), metric("retention", "Retention", "percentage", "driver"), metric("qualified_leads", "Qualified leads", "count", "driver")], growthLevers: ["occupancy", "lead_quality", "response_speed", "retention"], commonDataSources: STANDARD_SOURCES },
  dental: { id: "dental", label: "Dental practices", primaryGoal: getVerticalConfig("dental").primaryGoal, metrics: [metric("bookings", "Bookings", "count", "north_star"), metric("no_show_rate", "No-show rate", "percentage", "guardrail", "lower_is_better"), metric("retention", "Retention", "percentage", "driver"), metric("treatment_value", "Treatment value", "currency", "driver"), metric("reviews", "Reviews", "count", "driver")], growthLevers: ["booking_conversion", "no_show_reduction", "treatment_acceptance", "retention", "reputation"], commonDataSources: STANDARD_SOURCES },
  ecommerce: { id: "ecommerce", label: "E-commerce", primaryGoal: getVerticalConfig("ecommerce").primaryGoal, metrics: [metric("revenue", "Revenue", "currency", "north_star"), metric("conversion_rate", "Conversion rate", "percentage", "driver"), metric("aov", "Average order value", "currency", "driver"), metric("repeat_purchase_rate", "Repeat purchase rate", "percentage", "driver"), metric("contribution_margin", "Contribution margin", "percentage", "guardrail")], growthLevers: ["acquisition", "conversion", "aov", "retention", "margin"], commonDataSources: ["website", "analytics", "crm", "transactions", "advertising", "email"] },
  saas: { id: "saas", label: "SaaS", primaryGoal: getVerticalConfig("saas").primaryGoal, metrics: [metric("qualified_leads", "Qualified leads", "count", "driver"), metric("activation_rate", "Activation rate", "percentage", "driver"), metric("retention", "Retention", "percentage", "driver"), metric("churn", "Churn", "percentage", "guardrail", "lower_is_better"), metric("net_revenue_retention", "Net revenue retention", "percentage", "north_star")], growthLevers: ["acquisition", "activation", "retention", "expansion", "pricing"], commonDataSources: ["website", "product_analytics", "crm", "billing", "support"] },
  professional_services: { id: "professional_services", label: "Professional services", primaryGoal: getVerticalConfig("professional_services").primaryGoal, metrics: [metric("qualified_leads", "Qualified leads", "count", "driver"), metric("win_rate", "Win rate", "percentage", "driver"), metric("utilization", "Utilization", "percentage", "driver"), metric("average_contract_value", "Average contract value", "currency", "driver"), metric("gross_margin", "Gross margin", "percentage", "north_star")], growthLevers: ["pipeline", "proposal_conversion", "utilization", "pricing", "margin"], commonDataSources: STANDARD_SOURCES },
  local_services: { id: "local_services", label: "Local services", primaryGoal: getVerticalConfig("local_services").primaryGoal, metrics: [metric("qualified_leads", "Qualified leads", "count", "north_star"), metric("conversion_rate", "Conversion rate", "percentage", "driver"), metric("response_time", "Response time", "duration", "driver", "lower_is_better"), metric("reviews", "Reviews", "count", "driver"), metric("repeat_business", "Repeat business", "count", "driver")], growthLevers: ["local_demand", "conversion", "response_speed", "reviews", "retention"], commonDataSources: STANDARD_SOURCES },
  retail: { id: "retail", label: "Retail", primaryGoal: getVerticalConfig("retail").primaryGoal, metrics: [metric("revenue", "Revenue", "currency", "north_star"), metric("conversion_rate", "Conversion rate", "percentage", "driver"), metric("aov", "Average order value", "currency", "driver"), metric("gross_margin", "Gross margin", "percentage", "guardrail"), metric("repeat_customers", "Repeat customers", "count", "driver")], growthLevers: ["traffic", "conversion", "basket_size", "margin", "retention"], commonDataSources: STANDARD_SOURCES },
  health_wellness: { id: "health_wellness", label: "Health & wellness", primaryGoal: getVerticalConfig("health_wellness").primaryGoal, metrics: [metric("bookings", "Bookings", "count", "north_star"), metric("retention", "Retention", "percentage", "driver"), metric("no_show_rate", "No-show rate", "percentage", "guardrail", "lower_is_better"), metric("average_ticket", "Average ticket", "currency", "driver"), metric("reviews", "Reviews", "count", "driver")], growthLevers: ["booking_conversion", "retention", "no_show_reduction", "service_mix", "reputation"], commonDataSources: STANDARD_SOURCES },
  generic_business: { id: "generic_business", label: "General business", primaryGoal: getVerticalConfig("generic_business").primaryGoal, metrics: [metric("revenue", "Revenue", "currency", "north_star"), metric("conversion_rate", "Conversion rate", "percentage", "driver"), metric("retention", "Retention", "percentage", "driver"), metric("gross_margin", "Gross margin", "percentage", "guardrail"), metric("customer_value", "Customer value", "currency", "driver")], growthLevers: ["demand", "conversion", "retention", "pricing", "margin"], commonDataSources: STANDARD_SOURCES },
};

export function getIndustryAdapter(vertical?: string | null): IndustryAdapter {
  return ADAPTERS[(vertical as GrowthVerticalId) || "generic_business"] ?? ADAPTERS.generic_business;
}

export function listIndustryAdapters(): IndustryAdapter[] {
  return Object.values(ADAPTERS);
}
