export type GrowthVertical = "restaurant" | "hotel" | "barber" | "hairdresser" | "beauty" | "home_services" | "construction" | "professional_services";
export type GrowthStrategy = { vertical: GrowthVertical; primaryKpis: string[]; acquisitionChannels: string[]; conversionLevers: string[]; websiteProof: string[] };
const STRATEGIES: Record<GrowthVertical, GrowthStrategy> = {
  restaurant: { vertical: "restaurant", primaryKpis: ["reservations", "repeat_visits", "average_order_value"], acquisitionChannels: ["local_search", "social", "reviews"], conversionLevers: ["menu", "offers", "booking_cta"], websiteProof: ["menu", "reviews", "location", "opening_hours"] },
  hotel: { vertical: "hotel", primaryKpis: ["direct_bookings", "occupancy", "revenue_per_room"], acquisitionChannels: ["local_search", "direct", "retargeting"], conversionLevers: ["room_value", "availability", "booking_cta"], websiteProof: ["rooms", "amenities", "reviews", "location"] },
  barber: { vertical: "barber", primaryKpis: ["appointments", "repeat_visits", "average_ticket"], acquisitionChannels: ["local_search", "social", "referrals"], conversionLevers: ["portfolio", "availability", "booking_cta"], websiteProof: ["portfolio", "services", "reviews", "booking"] },
  hairdresser: { vertical: "hairdresser", primaryKpis: ["appointments", "repeat_visits", "average_ticket"], acquisitionChannels: ["local_search", "social", "referrals"], conversionLevers: ["portfolio", "services", "booking_cta"], websiteProof: ["portfolio", "services", "reviews", "booking"] },
  beauty: { vertical: "beauty", primaryKpis: ["appointments", "repeat_visits", "average_ticket"], acquisitionChannels: ["local_search", "social", "referrals"], conversionLevers: ["results", "availability", "booking_cta"], websiteProof: ["results", "services", "reviews", "booking"] },
  home_services: { vertical: "home_services", primaryKpis: ["qualified_leads", "quote_requests", "close_rate"], acquisitionChannels: ["local_search", "referrals", "paid_search"], conversionLevers: ["proof", "response_speed", "quote_cta"], websiteProof: ["services", "areas", "reviews", "quote"] },
  construction: { vertical: "construction", primaryKpis: ["qualified_leads", "quote_requests", "close_rate"], acquisitionChannels: ["local_search", "referrals", "paid_search"], conversionLevers: ["portfolio", "trust", "quote_cta"], websiteProof: ["projects", "certifications", "reviews", "quote"] },
  professional_services: { vertical: "professional_services", primaryKpis: ["qualified_leads", "consultations", "close_rate"], acquisitionChannels: ["search", "referrals", "content"], conversionLevers: ["authority", "proof", "consultation_cta"], websiteProof: ["expertise", "case_studies", "reviews", "contact"] },
};
export function getGrowthStrategy(vertical: GrowthVertical): GrowthStrategy { return STRATEGIES[vertical]; }
