import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
type Recommendation={title:string;rationale:string;priority:'low'|'medium'|'high'|'critical';actions:string[]};
type Result={score:number;summary:string;strengths:string[];issues:string[];opportunities:string[];recommendations:Recommendation[]};
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{
 const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return json({error:'Authentication required'},401);
 const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_ANON_KEY'),open=Deno.env.get('OPENROUTER_API_KEY'),model=Deno.env.get('GGA_AI_MODEL')||'openai/gpt-4o-mini';if(!url||!key)return json({error:'Supabase environment is incomplete'},500);if(!open)return json({error:'AI provider is not configured. Set OPENROUTER_API_KEY.'},503);
 const sb=createClient(url,key,{global:{headers:{Authorization:auth}}});const {data:{user}}=await sb.auth.getUser();if(!user)return json({error:'Invalid session'},401);const body=await req.json();const menuId=typeof body?.menu_id==='string'?body.menu_id:'';if(!menuId)return json({error:'menu_id is required'},400);
 const {data:menu,error:me}=await sb.from('menus').select('id,restaurant_id,name').eq('id',menuId).single();if(me||!menu)return json({error:'Menu not found'},404);
 const {data:items,error:ie}=await sb.from('menu_items').select('category,name,description,price,cost,position').eq('menu_id',menuId).order('position');if(ie)throw ie;if(!items?.length)return json({error:'Menu has no items'},400);
 const {data:restaurant,error:re}=await sb.from('restaurants').select('name,cuisine,city,country,price_segment,seats,average_ticket,target_customer,business_goals,current_problems').eq('id',menu.restaurant_id).single();if(re)throw re;
 const {data:member,error:memberError}=await sb.from('organization_members').select('organization_id').eq('user_id',user.id).limit(1).single();if(memberError||!member)return json({error:'Workspace access denied'},403);
 const system=`You are GGA Menu Intelligence, a senior restaurant menu engineer. Analyze only supplied data. Never invent sales, margin or popularity data. If evidence is missing, state the limitation. Evaluate pricing architecture, descriptions, category balance, perceived value, upsell/cross-sell opportunities and obvious menu engineering issues. Return JSON only: {"score":number,"summary":string,"strengths":string[],"issues":string[],"opportunities":string[],"recommendations":[{"title":string,"rationale":string,"priority":"low|medium|high|critical","actions":string[]}]}. Score 0-100. Give 2-5 strengths, 2-6 issues, 2-6 opportunities, 2-5 recommendations. Each recommendation has 2-4 concrete actions.`;
 const ai=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${open}`,'Content-Type':'application/json','HTTP-Referer':url,'X-Title':'Gastro Growth Advisor'},body:JSON.stringify({model,temperature:.15,response_format:{type:'json_object'},messages:[{role:'system',content:system},{role:'user',content:JSON.stringify({restaurant,menu,items})}]})});if(!ai.ok)return json({error:`AI provider error (${ai.status}).`},502);const payload=await ai.json(),raw=payload?.choices?.[0]?.message?.content;if(typeof raw!=='string')return json({error:'AI returned an empty response.'},502);let result:Result;try{result=JSON.parse(raw)}catch{return json({error:'AI returned invalid structured data.'},502)}
 result.score=Math.max(0,Math.min(100,Number(result.score)||50));for(const k of ['strengths','issues','opportunities'] as const)result[k]=Array.isArray(result[k])?result[k].slice(0,6).map(String):[];const allowed=new Set(['low','medium','high','critical']);result.recommendations=Array.isArray(result.recommendations)?result.recommendations.slice(0,5).map(r=>({title:String(r?.title||'Recommendation'),rationale:String(r?.rationale||''),priority:allowed.has(r?.priority)?r.priority:'medium',actions:Array.isArray(r?.actions)?r.actions.slice(0,4).map(String):[]})):[];
 await sb.from('menus').update({status:'analyzed',updated_at:new Date().toISOString()}).eq('id',menuId);const {data:saved,error:save}=await sb.from('menu_analyses').insert({menu_id:menuId,restaurant_id:menu.restaurant_id,user_id:user.id,score:result.score,summary:String(result.summary||''),strengths:result.strengths,issues:result.issues,opportunities:result.opportunities,recommendations:result.recommendations}).select('id,created_at').single();if(save)throw save;return json({analysis_id:saved.id,created_at:saved.created_at,...result});
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:'Unexpected menu analysis error.'},500)}});
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'Content-Type':'application/json'}})}
