import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const CORS={'Access-Control-Allow-Origin':'https://gastrogrowthadvisor.com','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'};
type Project={id:string;user_id:string;artifacts:Record<string,unknown>;version:number;active_stage:number;completed_stages:number[]};
const registry=['SiteHeader','Hero','Proof','FeatureGrid','Offer','Media','Timeline','Faq','Venue','About','Testimonials','Contact','Cta','Footer','Gallery','Stats'];

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return out({error:'Method not allowed'},405);try{const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return out({error:'Authentication required'},401);const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_ANON_KEY');if(!url||!key)throw new Error('Supabase environment is incomplete');const sb=createClient(url,key,{global:{headers:{Authorization:auth}}});const {data:{user}}=await sb.auth.getUser();if(!user)return out({error:'Invalid session'},401);const body=await req.json().catch(()=>null);const id=typeof body?.projectId==='string'?body.projectId:'';if(!id)return out({error:'projectId is required'},400);const found=await sb.from('website_builder_projects').select('*').eq('id',id).eq('user_id',user.id).single();if(found.error)throw found.error;const p=found.data as Project;const report=qa(p);const artifacts={...p.artifacts,QA:report};const passed=report.releaseGate!=='BLOCKED';const completed=Array.from(new Set([...(p.completed_stages??[]),...(passed?[9]:[])])).sort((a,b)=>a-b);const updated=await sb.from('website_builder_projects').update({artifacts,status:passed?'ready':'blocked',active_stage:passed?10:p.active_stage,completed_stages:completed,version:p.version+1}).eq('id',p.id).eq('user_id',user.id).select('*').single();if(updated.error)throw updated.error;return out({project:updated.data,qa:report},200)}catch(e){console.error('builder qa',e);return out({error:e instanceof Error?e.message:'QA failed'},502)}});
function qa(p:Project){const a=p.artifacts;const checks=[c('accessibility',Boolean(a['Component Generation']),'Component manifest must exist.'),c('responsive',Boolean(a['Responsive Renderer']),'Responsive renderer artifact must exist.'),c('links',Boolean(a['Page Architecture']),'Page architecture must exist.'),c('content',Boolean(a['Content Intelligence']),'Content intelligence must exist.'),c('runtime',Boolean(a['Component Generation']&&a['Responsive Renderer']),'Controlled component registry and renderer must exist.')];const manifest=a['Component Generation'] as Record<string,unknown>|undefined;const allowed=Array.isArray(manifest?.allowedComponents)?manifest.allowedComponents:[];const runtime=checks.find(x=>x.check==='runtime');if(runtime&&(!allowed.length||allowed.some(x=>!registry.includes(String(x))))){runtime.status='fail';runtime.score=0;runtime.findings=['Component manifest contains an unknown or empty component registry.']}const score=Math.round(checks.reduce((s,x)=>s+x.score,0)/checks.length);const releaseGate=checks.some(x=>x.status==='fail')?'BLOCKED':score>=90?'PASS':'PASS_WITH_WARNINGS';return{schemaVersion:'1.0',type:'qa-report',generatedAt:new Date().toISOString(),checks,score,releaseGate,notes:['Structural gate is complete. Browser-level screenshots, interaction, link target and runtime checks remain mandatory before production publish.']};}
function c(check:string,ok:boolean,message:string){return{check,status:ok?'pass':'fail',score:ok?100:0,findings:ok?[]:[message]};}
function out(body:unknown,status:number){return new Response(JSON.stringify(body),{status,headers:{...CORS,'Content-Type':'application/json'}})}
