import { callOpenRouter, parseJson } from './_shared/ai.ts';
import { getCorsHeaders } from './_shared/cors.ts';

type File={path:string;content:string}; type Site={projectName:string;stack:string;description:string;files:File[];previewHtml:string;designTokens:Record<string,unknown>;buildNotes:string[]};
Deno.serve(async(req)=>{const cors=getCorsHeaders(req);if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({error:'Method not allowed'},405,cors);try{const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return out({error:'Authentication required'},401,cors);const body=await req.json().catch(()=>null);const site=normalize(body?.site);if(site.files.length<4)return out({error:'At least four repository files are required.'},400,cors);const maxRepairs=Math.min(Math.max(Number(body?.maxRepairs)||2,0),3);let current=site;const reports=[];for(let attempt=0;attempt<=maxRepairs;attempt++){const report=staticAudit(current);reports.push(report);if(report.pass)return out({status:'verified',site:current,build:{type:'static_validation',pass:true,attempts:attempt+1,reports}},200,cors);if(attempt===maxRepairs)break;const repaired=await repair(current,report);current=mergeSite(current,repaired)}return out({status:'failed',site:current,build:{type:'static_validation',pass:false,attempts:reports.length,reports}},422,cors)}catch(e){return out({error:e instanceof Error?e.message:'Compile loop failed.'},502,cors)}});
function staticAudit(site:Site){const paths=new Set(site.files.map(f=>f.path));const errors:string[]=[];if(site.stack==='react-vite'){for(const p of ['package.json','index.html','src/main.tsx','src/App.tsx','src/index.css'])if(!paths.has(p))errors.push('missing:'+p);const pkg=site.files.find(f=>f.path==='package.json');if(pkg){try{const j=JSON.parse(pkg.content);if(j.scripts?.build!=='vite build')errors.push('package.json must expose build script vite build');if(!j.dependencies&&!j.devDependencies)errors.push('package.json dependencies missing')}catch{errors.push('package.json invalid JSON')}}for(const f of site.files.filter(f=>/\.(tsx?|jsx?)$/.test(f.path))){if(/from ['"](?!\.|react|react-dom|lucide-react)[^'"]+['"]/.test(f.content))errors.push('unresolved external import in '+f.path);const imports=[...f.content.matchAll(/from ['"](\.\.?\/[^'"]+)['"]/g)].map(m=>m[1]);for(const imp of imports){const base=resolve(f.path,imp);if(![base,base+'.ts',base+'.tsx',base+'.js',base+'.jsx',base+'/index.ts',base+'/index.tsx'].some(x=>paths.has(x)))errors.push('missing import '+imp+' in '+f.path)}}}if(!site.previewHtml.trim())errors.push('previewHtml missing');if(/<script[^>]+src=/i.test(site.previewHtml))errors.push('preview must not depend on external scripts');if(/\b(eval|Function)\s*\(/.test(site.previewHtml))errors.push('unsafe executable construct in preview');return{pass:errors.length===0,errors,checkedFiles:site.files.length}}
async function repair(site:Site,report:{errors:string[]}){const system='You are a deterministic website code repair compiler. Return JSON only: {files:[{path,content}],previewHtml?,buildNotes?}. Fix ONLY the reported errors. Preserve the visual design and requested behavior. Do not remove requested features merely to pass validation. Keep React/Vite imports resolvable and package scripts correct. Never use eval, Function, iframe, object, embed or remote script tags.';const ai=await callOpenRouter({task:'website',system,user:JSON.stringify({site,errors:report.errors}),temperature:0.1});return parseJson<{files:File[];previewHtml?:string;buildNotes?:string[]}>(ai.content)}
function mergeSite(site:Site,patch:{files?:File[];previewHtml?:string;buildNotes?:string[]}){const map=new Map(site.files.map(f=>[f.path,f]));for(const f of patch.files??[])if(validPath(f.path)&&f.content)map.set(f.path,{path:f.path,content:f.content});return{...site,files:[...map.values()].slice(0,40),previewHtml:typeof patch.previewHtml==='string'?patch.previewHtml:site.previewHtml,buildNotes:[...site.buildNotes,...(patch.buildNotes??[])].slice(-30)}}
function normalize(v:unknown):Site{const x=v&&typeof v==='object'?v as Record<string,unknown>:{};const files=Array.isArray(x.files)?x.files.map(v=>{const f=v&&typeof v==='object'?v as Record<string,unknown>:{};return{path:validPath(String(f.path??''))?String(f.path):'',content:typeof f.content==='string'?f.content.slice(0,60000):''}}).filter(f=>f.path&&f.content):[];return{projectName:String(x.projectName||'AI Website').slice(0,120),stack:x.stack==='static-html'?'static-html':'react-vite',description:String(x.description||'').slice(0,500),files,previewHtml:typeof x.previewHtml==='string'?x.previewHtml.slice(0,100000):'',designTokens:x.designTokens&&typeof x.designTokens==='object'?x.designTokens as Record<string,unknown>:{},buildNotes:Array.isArray(x.buildNotes)?x.buildNotes.filter(v=>typeof v==='string').slice(0,20):[]}}
function validPath(p:string){return p.length>0&&!p.startsWith('/')&&!p.includes('..')&&!p.includes('\\0')}
function resolve(file:string,imp:string){const a=file.split('/');a.pop();for(const part of imp.split('/')){if(part==='.')continue;if(part==='..')a.pop();else a.push(part)}return a.join('/')}
function out(body:unknown,status:number,cors:Record<string,string>){return new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}})}
