import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { requireSupabase } from "../lib/supabase";
import AppShell from "../components/AppShell";

export default function ActionsPage(){
 const [restaurantId,setRestaurantId]=useState<string>(); const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [running,setRunning]=useState(false); const [error,setError]=useState("");
 const supabase = requireSupabase(); const load=async()=>{setLoading(true); const {data:{user}}=await supabase.auth.getUser(); if(!user){setLoading(false);return;} const {data:m}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).limit(1).maybeSingle(); if(!m){setLoading(false);return;} const {data:r}=await supabase.from("restaurants").select("id").eq("organization_id",m.organization_id).limit(1).maybeSingle(); if(!r){setLoading(false);return;} setRestaurantId(r.id); const {data}=await supabase.from("recommendations").select("*").eq("restaurant_id",r.id).in("status",["pending","accepted"]).order("created_at",{ascending:false}); setItems(data??[]); setLoading(false);};
 useEffect(()=>{load()},[]);
 const generate=async()=>{if(!restaurantId)return;setRunning(true);setError("");const {data,error}=await supabase.functions.invoke("gga-recommendation-engine",{body:{restaurantId}});if(error||data?.error)setError(error?.message??data?.error??"Recommendation engine failed");await load();setRunning(false)};
 const accept=async(r:any)=>{setError("");const {error}=await supabase.from("recommendations").update({status:"accepted"}).eq("id",r.id);if(error){setError(error.message);return;}const result=await supabase.from("actions").insert({restaurant_id:r.restaurant_id,recommendation_id:r.id,action_type:r.action_payload?.type??"growth_action",title:r.title,description:r.rationale,status:"todo",priority:r.priority,payload:r.action_payload});if(result.error)setError(result.error.message);await load()};

 if(loading)return <AppShell title="Action Center"><div className="py-16 text-center text-zinc-500">Loading Action Center...</div></AppShell>;
 return <AppShell title="Action Center"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><Link to="/app/dashboard" className="text-sm text-zinc-500 hover:text-white">â† Dashboard</Link><h2 className="mt-2 text-4xl font-semibold tracking-tight">Action Center</h2><p className="mt-2 text-zinc-400">Turn intelligence into a prioritized execution backlog.</p></div><button onClick={generate} disabled={running} className="rounded-xl bg-violet-500 px-5 py-3 text-sm font-semibold disabled:opacity-50">{running?"Analyzing...":"Generate recommendations"}</button></div>{error&&<div className="mb-5 rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-sm text-amber-200">{error}</div>}<div className="grid gap-4">{items.length===0?<div className="rounded-2xl border border-dashed border-white/10 p-10 text-center"><h3 className="text-xl font-semibold">No pending recommendations</h3><p className="mt-2 text-zinc-500">Run the engine after adding Advisor, Menu or Review intelligence.</p></div>:items.map(r=><article key={r.id} className="rounded-2xl border border-white/10 bg-white/[0.025] p-6 transition hover:border-violet-400/20"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 text-xs uppercase tracking-wider text-violet-300/70">{r.source_type} Â· {r.priority}</div><h3 className="text-xl font-semibold">{r.title}</h3><p className="mt-2 max-w-3xl text-zinc-400">{r.rationale}</p></div><button onClick={()=>accept(r)} className="rounded-lg border border-white/10 px-4 py-2 text-sm hover:bg-white/5">Create action</button></div>{r.problem&&<p className="mt-4 text-sm text-zinc-300"><strong>Problem:</strong> {r.problem}</p>}{r.expected_impact&&<p className="mt-1 text-sm text-zinc-400"><strong>Impact:</strong> {r.expected_impact}</p>}</article>)}</div><ActionQueue restaurantId={restaurantId}/></AppShell>;
}
function ActionQueue({restaurantId}:{restaurantId?:string}){ const supabase = requireSupabase();const [actions,setActions]=useState<any[]>([]);useEffect(()=>{if(!restaurantId)return;supabase.from('actions').select('*').eq('restaurant_id',restaurantId).order('created_at',{ascending:false}).limit(12).then(({data})=>setActions(data??[]))},[restaurantId]);const execute=async(id:string)=>{await supabase.functions.invoke('gga-action-executor',{body:{actionId:id}});const {data}=await supabase.from('actions').select('*').eq('restaurant_id',restaurantId!).order('created_at',{ascending:false}).limit(12);setActions(data??[])};return <section className="mt-8"><div className="mb-4"><h3 className="text-xl font-semibold">Execution queue</h3><p className="mt-1 text-sm text-zinc-500">Internal actions execute now. External publishing waits for provider authorization.</p></div><div className="space-y-2">{actions.map(a=><div key={a.id} className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/[0.02] p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-medium">{a.title}</div><div className="mt-1 text-xs text-zinc-500">{a.action_type} Â· {a.status}</div></div>{['todo','approved'].includes(a.status)&&<button onClick={()=>execute(a.id)} className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-black">Execute</button>}</div>)}</div></section>}







