import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "../lib/supabase";

export default function ActionsPage(){
 const [restaurantId,setRestaurantId]=useState<string>(); const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [running,setRunning]=useState(false); const [error,setError]=useState("");
 const load=async()=>{setLoading(true); const {data:{user}}=await supabase.auth.getUser(); if(!user){setLoading(false);return;} const {data:m}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).limit(1).maybeSingle(); if(!m){setLoading(false);return;} const {data:r}=await supabase.from("restaurants").select("id").eq("organization_id",m.organization_id).limit(1).maybeSingle(); if(!r){setLoading(false);return;} setRestaurantId(r.id); const {data}=await supabase.from("recommendations").select("*").eq("restaurant_id",r.id).in("status",["pending","accepted"]).order("created_at",{ascending:false}); setItems(data??[]); setLoading(false);};
 useEffect(()=>{load()},[]);
 const generate=async()=>{if(!restaurantId)return;setRunning(true);setError("");const {data,error}=await supabase.functions.invoke("gga-recommendation-engine",{body:{restaurantId}});if(error||data?.error)setError(error?.message??data?.error??"Recommendation engine failed");await load();setRunning(false)};
 const accept=async(r:any)=>{await supabase.from("recommendations").update({status:"accepted"}).eq("id",r.id);const {error}=await supabase.from("actions").insert({restaurant_id:r.restaurant_id,recommendation_id:r.id,action_type:r.action_payload?.type??"growth_action",title:r.title,description:r.rationale,status:"todo",priority:r.priority,payload:r.action_payload});if(error)setError(error.message);await load()};
 if(loading)return <main className="min-h-screen p-8">Loading Action Center...</main>;
 return <main className="min-h-screen bg-background p-6 md:p-10"><div className="mx-auto max-w-6xl"><div className="mb-8 flex items-end justify-between gap-4"><div><Link to="/app/dashboard" className="text-sm opacity-60">← Dashboard</Link><h1 className="mt-2 text-4xl font-bold">Action Center</h1><p className="mt-2 opacity-70">Turn GGA intelligence into a prioritized execution backlog.</p></div><button onClick={generate} disabled={running} className="rounded-xl bg-foreground px-5 py-3 text-background disabled:opacity-50">{running?"Analyzing...":"Generate recommendations"}</button></div>{error&&<div className="mb-5 rounded-xl border p-4">{error}</div>}<div className="grid gap-4">{items.length===0?<div className="rounded-2xl border p-8"><h2 className="text-xl font-semibold">No pending recommendations</h2><p className="mt-2 opacity-70">Run the engine after adding Advisor, Menu or Review intelligence.</p></div>:items.map(r=><article key={r.id} className="rounded-2xl border bg-card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 text-xs uppercase tracking-wider opacity-60">{r.source_type} · {r.priority}</div><h2 className="text-xl font-semibold">{r.title}</h2><p className="mt-2 opacity-70">{r.rationale}</p></div><button onClick={()=>accept(r)} className="rounded-lg border px-4 py-2">Create action</button></div>{r.problem&&<p className="mt-4 text-sm"><strong>Problem:</strong> {r.problem}</p>}{r.expected_impact&&<p className="mt-1 text-sm"><strong>Impact:</strong> {r.expected_impact}</p>}</article>)}</div></div></main>;
}
