import { FormEvent, useEffect, useState } from 'react';
import { ArrowRight, Bot, CheckCircle2, ChevronRight, FlaskConical, Lightbulb, Loader2, ShieldCheck, Sparkles, Target } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { requireSupabase } from '../lib/supabase';
import AppShell from '../components/AppShell';

type Priority = 'low' | 'medium' | 'high' | 'critical';
type Recommendation = { id: string; title: string; rationale: string; priority: Priority; actions: string[]; expectedOutcome: string; confidence: number };
type Analysis = { analysisId: string; createdAt: string; problem: string; priority: Priority; confidence: number; diagnosis: { problem: string; rootCauses: string[]; impact: string; confidence: number }; evidence: Array<{ id: string; observation: string; epistemicStatus?: string; confidence: number }>; unknowns: string[]; hypotheses: Array<{ id: string; statement: string; rationale: string; confidence: number; status: string }>; opportunities: Array<{ id: string; title: string; description: string; impact: number; confidence: number; effort: number; risk: number; expectedOutcome?: string }>; decisions: Array<{ id: string; rationale: string; confidence: number; requiresApproval: boolean }>; recommendations: Recommendation[]; missionProposals: Array<{ id: string; objective: string; actions: string[]; expectedOutcome: string; risk: string; requiresApproval: boolean }>; expectedOutcomes: string[]; learningTargets: string[]; risks: string[] };

export default function AdvisorPage() {
  const { user, loading } = useAuth(); const navigate = useNavigate(); const [problem, setProblem] = useState(''); const [busy, setBusy] = useState(false); const [missionBusy, setMissionBusy] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState<Analysis | null>(null);
  useEffect(() => { if (!loading && !user) navigate('/login', { replace: true }); }, [loading, user, navigate]);
  async function submit(e: FormEvent) { e.preventDefault(); if (problem.trim().length < 8) { setError('Describe the business problem in at least 8 characters.'); return; } setBusy(true); setError(''); setResult(null); try { const { data, error } = await requireSupabase().functions.invoke('gga-advisor', { body: { problem: problem.trim() } }); if (error) { const context = (error as any)?.context; let detail = ''; if (context?.json) { try { const body = await context.json(); detail = body?.error ? String(body.error) : ''; } catch { /* Ignore malformed error context. */ } } throw new Error(detail || error.message || 'GA Advisor request failed.'); } if (data?.error) throw new Error(String(data.error)); setResult(data as Analysis); } catch (x) { setError(x instanceof Error ? x.message : 'GA analysis failed.'); } finally { setBusy(false); } }
  async function proposeMission() { if (!problem.trim()) return; setMissionBusy(true); setError(''); try { const { data, error } = await requireSupabase().functions.invoke('gga-growth-loop', { body: { problem: problem.trim() } }); if (error) throw new Error(error.message || 'Mission proposal failed.'); if (data?.error) throw new Error(String(data.error)); navigate('/app/missions'); } catch (x) { setError(x instanceof Error ? x.message : 'Mission proposal failed.'); } finally { setMissionBusy(false); } }
  if (loading || !user) return <AppShell title="AI Advisor"><div className="grid min-h-[60vh] place-items-center"><Loader2 className="animate-spin text-violet-300" size={34}/></div></AppShell>;
  return <AppShell title="AI Advisor"><div className="mx-auto max-w-6xl"><section className="relative overflow-hidden rounded-[30px] border border-white/[.08] bg-white/[.025] p-6 sm:p-8"><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-violet-600/15 blur-3xl"/><div className="pointer-events-none absolute -bottom-32 left-1/3 h-64 w-64 rounded-full bg-orange-500/10 blur-3xl"/><div className="relative max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-400/[.06] px-3 py-1 text-[10px] font-bold uppercase tracking-[.2em] text-violet-200"><Bot size={12}/> Business intelligence</div><h2 className="mt-4 text-3xl font-black tracking-tight text-white sm:text-5xl">Turn a business problem into a governed growth decision.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-zinc-400">GA separates evidence, hypotheses and unknowns, ranks opportunities, then prepares an approval-gated mission for the existing Growth Mission Engine.</p></div></section>
    <form onSubmit={submit} className="mt-5 rounded-3xl border border-white/[.08] bg-[#0b0c11] p-5 shadow-2xl sm:p-6"><div className="flex items-center justify-between gap-4"><label className="text-sm font-semibold text-white">What is the biggest growth problem right now?</label><span className="hidden text-[10px] uppercase tracking-wider text-zinc-600 sm:block">Evidence first · no invented metrics</span></div><textarea value={problem} onChange={e => setProblem(e.target.value)} maxLength={4000} rows={6} placeholder="Example: Revenue is flat, acquisition costs are rising, and repeat customers are declining." className="mt-3 w-full resize-y rounded-2xl border border-white/[.08] bg-[#07080c] px-4 py-4 text-sm leading-7 outline-none placeholder:text-zinc-600 focus:border-violet-400/50 focus:ring-4 focus:ring-violet-400/[.06]"/><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><span className="text-xs text-zinc-600">Include symptom, timing, business impact and evidence you already have.</span><button disabled={busy} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-violet-400 to-orange-300 px-5 py-3 text-sm font-black text-black shadow-lg transition hover:-translate-y-0.5 disabled:opacity-50">{busy ? <Loader2 size={16} className="animate-spin"/> : <Sparkles size={16}/>} {busy ? 'Analyzing...' : 'Analyze with GA'} <ChevronRight size={16}/></button></div>{error && <p role="alert" className="mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}</form>
    {result && <div className="mt-5 space-y-5"><section className="rounded-3xl border border-white/[.08] bg-white/[.025] p-6 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-violet-300">Diagnosis</p><h3 className="mt-2 text-xl font-bold text-white">Evidence-constrained growth diagnosis</h3></div><span className="rounded-full border border-violet-400/20 bg-violet-400/[.05] px-3 py-1 text-xs uppercase text-violet-200">{result.priority} · {result.confidence}% confidence</span></div><p className="mt-5 max-w-3xl text-sm leading-7 text-zinc-300">{result.diagnosis.impact}</p><div className="mt-5 grid gap-3 md:grid-cols-2"><div className="rounded-2xl border border-white/[.07] bg-black/20 p-4"><div className="flex items-center gap-2 text-xs uppercase tracking-wider text-zinc-500"><ShieldCheck size={14}/> Evidence</div>{result.evidence.map(e => <p key={e.id} className="mt-3 text-sm text-zinc-300">{e.observation}<span className="ml-2 text-xs text-zinc-600">{e.epistemicStatus || 'fact'} · {e.confidence}%</span></p>)}</div><div className="rounded-2xl border border-white/[.07] bg-black/20 p-4"><div className="flex items-center gap-2 text-xs uppercase tracking-wider text-zinc-500"><Target size={14}/> Root causes</div>{result.diagnosis.rootCauses.map(c => <p key={c} className="mt-3 text-sm text-zinc-300">{c}</p>)}</div></div></section>
      <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-white/[.08] bg-white/[.025] p-6"><div className="flex items-center gap-2 text-xs uppercase tracking-wider text-zinc-500"><FlaskConical size={14}/> Hypotheses</div>{result.hypotheses.map(h => <div key={h.id} className="mt-4 rounded-2xl border border-white/[.07] bg-black/20 p-4"><p className="text-sm font-medium text-white">{h.statement}</p><p className="mt-2 text-xs leading-5 text-zinc-500">{h.rationale}</p><span className="mt-3 inline-flex text-[10px] uppercase text-violet-300">{h.status} · {h.confidence}% confidence</span></div>)}</div><div className="rounded-3xl border border-white/[.08] bg-white/[.025] p-6"><div className="flex items-center gap-2 text-xs uppercase tracking-wider text-zinc-500"><Lightbulb size={14}/> Opportunities</div>{result.opportunities.map(o => <div key={o.id} className="mt-4 rounded-2xl border border-orange-400/10 bg-orange-400/[.03] p-4"><div className="flex justify-between gap-3"><p className="text-sm font-medium text-white">{o.title}</p><span className="text-xs text-orange-300">{o.impact}/100</span></div><p className="mt-2 text-xs leading-5 text-zinc-400">{o.description}</p><p className="mt-2 text-[10px] uppercase text-zinc-600">confidence {o.confidence}% · effort {o.effort} · risk {o.risk}</p></div>)}</div></section>
      <section className="grid gap-5 lg:grid-cols-2">{result.recommendations.map(r => <section key={r.id} className="rounded-3xl border border-white/[.08] bg-white/[.025] p-6"><div className="flex items-start justify-between gap-3"><h3 className="font-semibold text-white">{r.title}</h3><span className="text-xs uppercase text-violet-300">{r.priority}</span></div><p className="mt-3 text-sm leading-6 text-zinc-400">{r.rationale}</p><div className="mt-5 space-y-2">{r.actions.map(a => <div key={a} className="flex gap-2 text-sm text-zinc-300"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-violet-300"/>{a}</div>)}</div></section>)}</section>
      <section className="relative overflow-hidden rounded-3xl border border-orange-400/20 bg-orange-400/[.035] p-6"><div className="pointer-events-none absolute -right-16 -top-16 h-48 w-48 rounded-full bg-orange-400/10 blur-3xl"/><div className="relative flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-white"><Target size={16} className="text-orange-300"/> Decision → governed mission proposal</div><p className="mt-1 text-xs text-zinc-500">GA creates a mission run in the existing Mission Engine. Nothing executes without governance.</p>{result.unknowns.length > 0 && <p className="mt-3 text-xs text-zinc-500">Unknowns: {result.unknowns.join(' · ')}</p>}</div><button onClick={() => void proposeMission()} disabled={missionBusy} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-black text-black disabled:opacity-50">{missionBusy ? <Loader2 size={16} className="animate-spin"/> : <Target size={16}/>} {missionBusy ? 'Preparing mission...' : 'Prepare governed mission'} <ArrowRight size={15}/></button></div></section>
      <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-white/[.07] bg-white/[.02] p-5"><p className="text-[10px] uppercase tracking-wider text-zinc-500">Learning targets</p>{result.learningTargets.map(t => <p key={t} className="mt-2 text-sm text-zinc-300">{t}</p>)}</div><div className="rounded-2xl border border-white/[.07] bg-white/[.02] p-5"><p className="text-[10px] uppercase tracking-wider text-zinc-500">Risk boundary</p>{result.risks.map(r => <p key={r} className="mt-2 text-sm text-zinc-300">{r}</p>)}</div></div></div>}
  </div></AppShell>;
}
