import { Link } from 'react-router-dom';
import { ArrowRight, BrainCircuit, Check, ChevronRight, CircleDot, LineChart, Network, Sparkles } from 'lucide-react';

const moat = [
  ['Universal Intelligence Core','One reasoning and decision layer can serve multiple business models.'],
  ['Closed Growth Loop','Diagnosis, decisions, missions, execution, measurement and learning share one loop.'],
  ['Evidence-first reasoning','Facts, observations, hypotheses and unknowns are explicitly separated.'],
  ['Controlled autonomy','High-impact actions remain behind permissions, approval, policy and auditability.'],
];
const roadmap = ['Universal Business Core','Multi-model Intelligence','Business Memory + Learning','Industry Adapters','Data & SaaS Integrations','Controlled Autonomous Growth'];
const spine = ['BUSINESS CONTEXT','SIGNALS','EVIDENCE','DIAGNOSIS','OPPORTUNITY','DECISION','MISSION','APPROVAL','EXECUTION','MEASUREMENT','OUTCOME','LEARNING'];

export default function InvestorPage(){
 return <main className="min-h-screen overflow-x-hidden bg-[#07080c] text-slate-300 selection:bg-violet-400/30">
  <div className="pointer-events-none fixed inset-0 -z-10 bg-[radial-gradient(circle_at_20%_0%,rgba(124,58,237,.18),transparent_34%),radial-gradient(circle_at_90%_20%,rgba(249,115,22,.08),transparent_28%)]"/>
  <header className="sticky top-0 z-50 border-b border-white/[.06] bg-[#07080c]/85 backdrop-blur-xl"><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link to="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl border border-violet-400/30 bg-violet-500/10 text-violet-200"><Sparkles size={17}/></span><div><b className="text-white">GA</b><div className="text-[9px] uppercase tracking-[.18em] text-slate-600">Investor Brief</div></div></Link><div className="flex items-center gap-3"><Link to="/" className="hidden text-sm text-slate-400 hover:text-white sm:block">Platform</Link><Link to="/login" className="text-sm text-slate-400 hover:text-white">Login</Link><Link to="/signup" className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-950">Request access</Link></div></nav></header>
  <section className="px-5 pb-24 pt-20 lg:px-8 lg:pt-28"><div className="mx-auto max-w-7xl"><div className="max-w-4xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.035] px-3.5 py-2 text-xs"><CircleDot size={13} className="text-emerald-400"/> INVESTOR OVERVIEW</div><h1 className="text-5xl font-semibold tracking-[-.05em] text-white sm:text-6xl lg:text-7xl lg:leading-[1.02]">GA is building the intelligence layer for business growth.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-400">Businesses generate more signals than their teams can consistently interpret. GA turns fragmented business data into evidence-based decisions, measurable missions and a continuously learning growth system.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/signup" className="inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-semibold text-slate-950">Explore the product <ArrowRight size={16}/></Link><a href="#thesis" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-6 py-3.5 text-sm font-semibold text-white">Investment thesis <ChevronRight size={16}/></a></div></div></div></section>
  <section id="thesis" className="border-y border-white/[.06] bg-white/[.015] px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><div className="text-xs uppercase tracking-[.2em] text-violet-300">The thesis</div><h2 className="mt-4 text-3xl font-semibold text-white sm:text-5xl">AI should operate the growth loop, not just answer questions.</h2></div><div className="grid gap-4 sm:grid-cols-2">{[['01','Signals','Web, customers, sales, marketing, operations and financial signals enter one context layer.'],['02','Intelligence','Evidence is separated from assumptions and the highest-value growth constraints are diagnosed.'],['03','Decision','Opportunities are ranked by expected impact, confidence, effort, risk and time-to-signal.'],['04','Execution','Approved decisions become missions, actions and measurable outcomes.']].map(([n,t,d])=><div key={n} className="rounded-2xl border border-white/[.07] bg-[#0b0d12] p-6"><div className="font-mono text-xs text-slate-600">{n}</div><h3 className="mt-5 text-lg font-semibold text-white">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{d}</p></div>)}</div></div></div></section>
  <section className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><div className="text-xs uppercase tracking-[.2em] text-cyan-300">Platform architecture</div><h2 className="mt-4 text-3xl font-semibold text-white sm:text-5xl">One core, many businesses, one learning loop.</h2></div><div className="mt-10 overflow-hidden rounded-3xl border border-white/[.07] bg-[#0b0d12] p-6 sm:p-10"><div className="flex flex-wrap items-center gap-2">{spine.map((x,i)=><span key={x} className="flex items-center gap-2"><span className="rounded-lg border border-white/[.07] bg-white/[.025] px-2.5 py-2 font-mono text-[10px] text-slate-300 sm:text-xs">{x}</span>{i<spine.length-1&&<ChevronRight size={13} className="text-slate-700"/>}</span>)}</div><div className="mt-8 grid gap-5 border-t border-white/[.06] pt-8 md:grid-cols-3"><div><Network className="text-violet-300" size={20}/><b className="mt-4 block text-sm text-white">Business Knowledge</b><p className="mt-2 text-xs leading-5 text-slate-500">Identity, economics, customers, products, channels, constraints and goals.</p></div><div><BrainCircuit className="text-cyan-300" size={20}/><b className="mt-4 block text-sm text-white">Intelligence Orchestration</b><p className="mt-2 text-xs leading-5 text-slate-500">AI capabilities can be routed by task, quality, cost and availability.</p></div><div><LineChart className="text-emerald-300" size={20}/><b className="mt-4 block text-sm text-white">Outcome Memory</b><p className="mt-2 text-xs leading-5 text-slate-500">Predictions are compared with actual results so interventions become learnable.</p></div></div></div></div></section>
  <section className="border-y border-white/[.06] bg-white/[.015] px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="text-xs uppercase tracking-[.2em] text-violet-300">Defensibility</div><h2 className="mt-4 text-3xl font-semibold text-white sm:text-5xl">The moat is the system, not the prompt.</h2><div className="mt-10 grid gap-4 md:grid-cols-2">{moat.map(([t,d])=><div key={t} className="rounded-2xl border border-white/[.07] bg-[#0b0d12] p-7"><div className="mb-5 grid h-10 w-10 place-items-center rounded-xl bg-white/[.04] text-violet-200"><Check size={18}/></div><h3 className="text-lg font-semibold text-white">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{d}</p></div>)}</div></div></section>
  <section className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><div className="text-xs uppercase tracking-[.2em] text-orange-300">Expansion</div><h2 className="mt-4 text-3xl font-semibold text-white sm:text-5xl">Start vertical. Expand through the core.</h2><p className="mt-5 leading-7 text-slate-500">Restaurant intelligence is the first proving ground, not the product boundary. Industry adapters add domain-specific entities, metrics, benchmarks and connectors while the intelligence core remains shared.</p></div><div className="grid gap-3">{roadmap.map((x,i)=><div key={x} className="flex items-center gap-4 rounded-2xl border border-white/[.07] bg-[#0b0d12] p-5"><span className="font-mono text-xs text-slate-600">0{i+1}</span><span className="text-sm font-semibold text-white">{x}</span><span className="ml-auto h-1.5 w-20 overflow-hidden rounded-full bg-white/5"><span className="block h-full rounded-full bg-gradient-to-r from-violet-400 to-orange-300" style={{width:`${Math.max(24,100-i*13)}%`}}/></span></div>)}</div></div></div></section>
  <section className="px-5 pb-24 pt-4 lg:px-8"><div className="mx-auto max-w-7xl overflow-hidden rounded-3xl border border-violet-400/15 bg-[radial-gradient(circle_at_80%_20%,rgba(124,58,237,.18),transparent_35%),#0b0d12] p-8 sm:p-12"><div className="grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="text-xs uppercase tracking-[.2em] text-violet-300">The opportunity</div><h2 className="mt-4 max-w-3xl text-3xl font-semibold text-white sm:text-5xl">Build the operating layer between business data and business action.</h2><p className="mt-5 max-w-2xl leading-7 text-slate-500">GA compounds: more context improves diagnosis, more missions create outcome data, and more outcomes improve future decisions.</p></div><Link to="/signup" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-slate-950">Request access <ArrowRight size={15}/></Link></div></div></section>
  <footer className="border-t border-white/[.06] px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-xs text-slate-600 sm:flex-row sm:items-center sm:justify-between"><span>GA — Universal Business Operating System</span><span>Confidential investor overview · Product architecture subject to change</span></div></footer>
 </main>;
}
