import { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, Loader2, Sparkles, Utensils } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { requireSupabase } from '../lib/supabase';
import AppShell from '../components/AppShell';

type MenuItem={name:string;category:string;description:string;price:number|null};
type Recommendation={title:string;rationale:string;priority:string;actions:string[]};
type Result={analysis_id:string;score:number;summary:string;strengths:string[];issues:string[];opportunities:string[];recommendations:Recommendation[]};
const example='STARTERS\nBruschetta al Pomodoro | 28 | Toasted sourdough, tomato, basil, extra virgin olive oil\nBurrata | 39 | Creamy burrata, roasted tomatoes, basil oil\n\nMAINS\nTagliatelle Bolognese | 49 | Fresh pasta, beef and pork ragu, parmesan\nGrilled Sea Bass | 72 | Seasonal vegetables, lemon butter\n\nDESSERTS\nTiramisu | 29 | Mascarpone, espresso, cocoa';
function parseMenu(text:string):MenuItem[]{const items:MenuItem[]=[];let category='Other';for(const line of text.split(/\r?\n/)){const s=line.trim();if(!s)continue;if(!s.includes('|')){category=s.replace(/[:]+$/,'').trim();continue}const p=s.split('|').map(x=>x.trim());const price=Number(p[1]);items.push({category,name:p[0],price:Number.isFinite(price)?price:null,description:p.slice(2).join(' | ')})}return items;}

export default function MenuPage(){
 const {user,loading}=useAuth();const navigate=useNavigate();const [menu,setMenu]=useState(example);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<Result|null>(null);
 useEffect(()=>{if(!loading&&!user)navigate('/login',{replace:true})},[loading,user,navigate]);
 async function submit(e:FormEvent){e.preventDefault();const items=parseMenu(menu);if(items.length<2){setError('Add at least two menu items. Use: Item | price | description');return}setBusy(true);setError('');setResult(null);try{const supabase=requireSupabase();const {data:members,error:me}=await supabase.from('organization_members').select('organization_id').eq('user_id',user!.id).limit(1);if(me)throw me;const org=members?.[0]?.organization_id;if(!org)throw new Error('No business workspace found. Complete onboarding first.');const {data:restaurant,error:re}=await supabase.from('restaurants').select('id').eq('organization_id',org).limit(1).single();if(re)throw re;const {data:m,error:mi}=await supabase.from('menus').insert({restaurant_id:restaurant.id,name:'Main Menu',source_type:'manual',raw_text:menu,status:'analyzing'}).select('id').single();if(mi)throw mi;const {error:ii}=await supabase.from('menu_items').insert(items.map((x,i)=>({menu_id:m.id,category:x.category,name:x.name,description:x.description,price:x.price,position:i})));if(ii)throw ii;const {data:ai,error:ae}=await supabase.functions.invoke('gga-menu-analyzer',{body:{menu_id:m.id}});if(ae)throw ae;if(ai?.error)throw new Error(ai.error);setResult(ai)}catch(x){setError(x instanceof Error?x.message:'Menu analysis failed.')}finally{setBusy(false)}}
 if(loading||!user)return <AppShell title="Menu Intelligence"><div className="grid min-h-[60vh] place-items-center"><Loader2 className="animate-spin text-violet-300" size={34}/></div></AppShell>;
 return <AppShell title="Menu Intelligence"><div className="mx-auto max-w-6xl"><section className="relative overflow-hidden rounded-[30px] border border-white/[.08] bg-white/[.025] p-6 sm:p-8"><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-violet-600/12 blur-3xl"/><div className="relative"><div className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-violet-300"><Utensils size={13}/> AI menu engineering</div><h2 className="mt-3 text-3xl font-black tracking-tight text-white sm:text-5xl">Turn your menu into a growth asset.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-zinc-400">Paste your menu. GA stores the structure, analyzes pricing and descriptions, then returns prioritized improvements.</p></div></section>
 <form onSubmit={submit} className="mt-5 grid gap-5 lg:grid-cols-[1fr_360px]"><section className="rounded-3xl border border-white/[.08] bg-[#0b0c11] p-5 shadow-2xl"><label className="text-sm font-semibold text-white">Menu data</label><p className="mt-1 text-xs text-zinc-600">Format: Item | price | description. Put category names on separate lines.</p><textarea value={menu} onChange={e=>setMenu(e.target.value)} rows={18} className="mt-4 w-full rounded-2xl border border-white/[.08] bg-[#07080c] p-4 font-mono text-sm leading-6 text-zinc-200 outline-none focus:border-violet-400/50"/><div className="mt-4 flex items-center justify-between gap-4"><span className="text-xs text-zinc-600">{parseMenu(menu).length} items detected</span><button disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-400 to-orange-300 px-5 py-3 text-sm font-black text-black disabled:opacity-50">{busy?<Loader2 size={16} className="animate-spin"/>:<Sparkles size={16}/>} {busy?'Analyzing...':'Analyze menu'}</button></div>{error&&<p role="alert" className="mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}</section><aside className="rounded-3xl border border-white/[.08] bg-white/[.025] p-5"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-zinc-500">Analysis scope</p><div className="mt-4 space-y-3 text-sm text-zinc-300"><div>Pricing and price architecture</div><div>Category structure</div><div>Descriptions and perceived value</div><div>Upsell and cross-sell opportunities</div><div>Weak menu items and priorities</div></div></aside></form>
 {result&&<div className="mt-8 space-y-5"><section className="rounded-3xl border border-white/[.08] bg-white/[.025] p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[10px] uppercase tracking-wider text-zinc-500">Menu health</p><p className="mt-2 text-5xl font-black text-white">{result.score}<span className="text-xl text-zinc-600">/100</span></p></div><div className="max-w-2xl text-sm leading-7 text-zinc-300">{result.summary}</div></div></section><div className="grid gap-5 md:grid-cols-3">{[['Strengths',result.strengths],['Issues',result.issues],['Opportunities',result.opportunities]].map(([title,list])=><section key={title as string} className="rounded-3xl border border-white/[.08] bg-white/[.025] p-5"><h2 className="font-semibold text-white">{title as string}</h2><div className="mt-4 space-y-3">{(list as string[]).map(x=><div key={x} className="text-sm leading-6 text-zinc-400">{x}</div>)}</div></section>)}</div><section><h2 className="mb-4 text-xl font-semibold text-white">Priority recommendations</h2><div className="grid gap-5 md:grid-cols-2">{result.recommendations.map(r=><article key={r.title} className="rounded-3xl border border-white/[.08] bg-white/[.025] p-5"><div className="flex justify-between gap-3"><h3 className="font-semibold text-white">{r.title}</h3><span className="text-xs uppercase text-violet-300">{r.priority}</span></div><p className="mt-3 text-sm leading-6 text-zinc-400">{r.rationale}</p><div className="mt-4 space-y-2">{r.actions.map(a=><div key={a} className="flex gap-2 text-sm text-zinc-300"><CheckCircle2 size={15} className="mt-0.5 shrink-0 text-violet-300"/>{a}</div>)}</div></article>)}</div></section></div>}
 </div></AppShell>;
}
