import { FormEvent, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Loader2, Monitor, Palette, ShieldCheck, Smartphone, Sparkles, WandSparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { requireSupabase } from '../lib/supabase';
import type { GrowthVertical } from '../domain/verticalGrowthStrategy';

type Preview={sourceUrl:string;businessName:string;vertical:string;positioning:string;headline:string;subheadline:string;primaryCta:string;improvements:string[];palette:{background:string;accent:string;text:string};confidence:number};
type Gate={eligible:boolean;score:number;confidence:number;blockers:string[]};
const verticals:Array<{value:GrowthVertical;label:string}>=[{value:'restaurant',label:'Restaurant'},{value:'hotel',label:'Hotel'},{value:'barber',label:'Barber'},{value:'hairdresser',label:'Hairdresser'},{value:'beauty',label:'Beauty'},{value:'home_services',label:'Home services'},{value:'construction',label:'Construction'},{value:'professional_services',label:'Professional services'}];

export default function WebsitePreviewPage(){
 const[url,setUrl]=useState('');const[vertical,setVertical]=useState<GrowthVertical>('restaurant');const[busy,setBusy]=useState(false);const[requesting,setRequesting]=useState(false);const[error,setError]=useState('');const[requestStatus,setRequestStatus]=useState('');const[sessionId,setSessionId]=useState<string|null>(null);const[gate,setGate]=useState<Gate|null>(null);const[preview,setPreview]=useState<Preview|null>(null);const[device,setDevice]=useState<'desktop'|'mobile'>('desktop');
 async function submit(e:FormEvent){e.preventDefault();setError('');setRequestStatus('');setPreview(null);setGate(null);setSessionId(null);let normalized=url.trim();if(!/^https?:\/\//i.test(normalized))normalized=`https://${normalized}`;try{const parsed=new URL(normalized);if(!['http:','https:'].includes(parsed.protocol))throw new Error();normalized=parsed.toString()}catch{setError('Enter a valid website URL, for example https://example.com.');return}setBusy(true);try{const{data,error:invokeError}=await requireSupabase().functions.invoke('gga-website-preview',{body:{url:normalized,vertical}});if(invokeError)throw invokeError;if(data?.error)throw new Error(data.error);if(!data?.preview)throw new Error('The website analysis returned no preview.');setPreview(data.preview as Preview);if(data.audit?.trust){setGate({eligible:Boolean(data.audit.trust.eligible),score:Number(data.audit.score??0),confidence:Number(data.audit.trust.confidence??0),blockers:Array.isArray(data.audit.trust.blockers)?data.audit.trust.blockers:[]})}if(typeof data.session_id==='string')setSessionId(data.session_id)}catch(x){setError(x instanceof Error?x.message:'Website analysis failed.')}finally{setBusy(false)}}
 async function requestRebuild(){if(!sessionId||!gate?.eligible)return;setRequesting(true);setError('');setRequestStatus('');try{const{data,error:invokeError}=await requireSupabase().functions.invoke('gga-website-rebuild-request',{body:{session_id:sessionId}});if(invokeError)throw invokeError;if(data?.error)throw new Error(data.error);setRequestStatus(`Rebuild request ${data.status}. ID: ${data.request_id}`)}catch(x){setError(x instanceof Error?x.message:'Rebuild request failed.')}finally{setRequesting(false)}}
 const selectedVertical=verticals.find(i=>i.value===vertical)?.label??'Restaurant';
 return <main className="min-h-screen bg-[#07080c] text-white"><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8"><header className="flex items-center justify-between"><Link to="/app/dashboard" className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-white"><ArrowLeft size={16}/> Dashboard</Link><span className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-violet-300"><WandSparkles size={14}/> Website Vision AI</span></header>
 <section className="mx-auto max-w-3xl py-14 text-center sm:py-20"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl border border-violet-400/20 bg-violet-400/10 text-violet-200"><Sparkles size={21}/></div><p className="mt-6 text-xs font-semibold uppercase tracking-[0.22em] text-violet-300">Before → After</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-6xl">See what your website could become.</h1><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-zinc-400 sm:text-base">Paste your current website. GGA analyzes its structure and positioning, then creates a conversion-focused redesign concept for your business.</p>
 <form onSubmit={submit} className="mx-auto mt-9 rounded-2xl border border-white/10 bg-white/[0.035] p-3"><div className="flex flex-col gap-3 sm:flex-row"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://your-business.com" aria-label="Current website URL" inputMode="url" autoComplete="url" required className="min-h-12 flex-1 rounded-xl bg-black/30 px-4 text-sm outline-none placeholder:text-zinc-600 focus:ring-1 focus:ring-violet-400/60"/><select value={vertical} onChange={e=>setVertical(e.target.value as GrowthVertical)} aria-label="Business type" className="min-h-12 rounded-xl bg-black/30 px-4 text-sm text-zinc-200 outline-none focus:ring-1 focus:ring-violet-400/60">{verticals.map(i=><option key={i.value} value={i.value}>{i.label}</option>)}</select><button type="submit" disabled={busy} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 text-sm font-semibold text-black disabled:opacity-50">{busy?<Loader2 size={16} className="animate-spin"/>:<WandSparkles size={16}/>} {busy?'Analyzing site...':'Build my future site'} <ArrowRight size={15}/></button></div></form><p className="mt-3 text-xs text-zinc-600">Analysis profile: {selectedVertical}</p>{error&&<p role="alert" className="mx-auto mt-4 max-w-2xl rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}{requestStatus&&<p role="status" className="mx-auto mt-4 max-w-2xl rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm text-emerald-200">{requestStatus}</p>}</section>
 {preview&&<section className="pb-16"><div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[0.18em] text-zinc-500">AI redesign concept</p><h2 className="mt-2 text-2xl font-semibold">{preview.businessName}</h2><p className="mt-1 text-sm text-zinc-500">{preview.positioning}</p></div><div className="flex items-center gap-3"><div className="flex rounded-xl border border-white/10 bg-white/[0.03] p-1"><button type="button" onClick={()=>setDevice('desktop')} className={`rounded-lg p-2 ${device==='desktop'?'bg-white text-black':'text-zinc-500'}`} aria-label="Desktop preview"><Monitor size={17}/></button><button type="button" onClick={()=>setDevice('mobile')} className={`rounded-lg p-2 ${device==='mobile'?'bg-white text-black':'text-zinc-500'}`} aria-label="Mobile preview"><Smartphone size={17}/></button></div>{gate&&<span className={`inline-flex items-center gap-1 rounded-full border px-3 py-2 text-xs ${gate.eligible?'border-emerald-400/20 bg-emerald-400/10 text-emerald-300':'border-amber-400/20 bg-amber-400/10 text-amber-300'}`}><ShieldCheck size={14}/> {gate.eligible?'Demo verified':'Review required'}</span>}</div></div>
 <div className="grid gap-5 lg:grid-cols-[1fr_330px]"><div className="overflow-hidden rounded-3xl border border-white/10 bg-zinc-950 p-2 shadow-2xl"><div className={`mx-auto overflow-hidden rounded-2xl border border-black/10 bg-white text-zinc-900 ${device==='mobile'?'max-w-[390px]':'w-full'}`}><div className="flex items-center justify-between border-b px-5 py-3 text-[11px] text-zinc-400"><span>{preview.sourceUrl.replace(/^https?:\/\//,'').replace(/\/$/,'')}</span><span>GGA FUTURE PREVIEW</span></div><div className="min-h-[430px] px-7 py-10 sm:px-12 sm:py-14" style={{background:preview.palette.background,color:preview.palette.text}}><div className="flex items-center justify-between gap-4"><span className="font-bold tracking-tight">{preview.businessName}</span><span className="hidden rounded-full px-3 py-1 text-xs sm:inline-flex" style={{background:preview.palette.accent,color:'#fff'}}>{preview.primaryCta}</span></div><div className="mx-auto max-w-2xl py-20 text-center"><div className="mx-auto mb-5 inline-flex rounded-full border px-3 py-1 text-[10px] uppercase tracking-[0.18em] opacity-60">{preview.vertical}</div><h3 className="text-4xl font-black tracking-tight sm:text-6xl">{preview.headline}</h3><p className="mx-auto mt-5 max-w-xl text-sm leading-6 opacity-65 sm:text-base">{preview.subheadline}</p><button type="button" className="mt-8 rounded-xl px-6 py-3 text-sm font-bold text-white shadow-lg" style={{background:preview.palette.accent}}>{preview.primaryCta}</button></div><div className="grid grid-cols-3 gap-2 border-t border-black/10 pt-5"><div className="h-2 rounded bg-black/10"/><div className="h-2 rounded bg-black/10"/><div className="h-2 rounded bg-black/10"/></div></div></div></div>
 <aside className="space-y-4"><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-center gap-2 text-sm font-semibold"><Palette size={16} className="text-violet-300"/> Visual direction</div><div className="mt-4 flex gap-2"><span className="h-8 w-8 rounded-lg border border-white/10" style={{background:preview.palette.background}}/><span className="h-8 w-8 rounded-lg" style={{background:preview.palette.accent}}/><span className="h-8 w-8 rounded-lg" style={{background:preview.palette.text}}/></div><p className="mt-3 text-xs text-zinc-500">AI-selected palette based on business positioning.</p></div>
 <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="text-xs uppercase tracking-[0.16em] text-zinc-500">Why it is better</div><div className="mt-4 space-y-3">{preview.improvements.map(item=><div key={item} className="flex gap-2 text-sm text-zinc-300"><Check size={16} className="mt-0.5 shrink-0 text-emerald-400"/>{item}</div>)}</div></div>
 <div className="rounded-2xl border border-violet-400/15 bg-violet-400/[0.05] p-5"><div className="text-xs uppercase tracking-[0.16em] text-violet-300">Server trust gate</div><div className="mt-2 text-3xl font-semibold">{gate?`${gate.score}/100`:'...'}</div>{gate&&<p className="mt-2 text-xs text-zinc-500">Confidence {Math.round(gate.confidence*100)}%. {gate.eligible?'Eligible for rebuild request.':'Rebuild blocked until critical findings are resolved.'}</p>}{gate&&gate.blockers.length>0&&<div className="mt-3 rounded-xl border border-amber-400/10 bg-amber-400/[0.04] p-3"><p className="text-xs font-semibold text-amber-300">Server blockers</p><ul className="mt-2 space-y-1 text-xs leading-5 text-zinc-400">{gate.blockers.slice(0,4).map(b=><li key={b}>• {b}</li>)}</ul></div>}<button type="button" onClick={requestRebuild} disabled={!gate?.eligible||!sessionId||requesting} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-black disabled:cursor-not-allowed disabled:opacity-40">{requesting?<Loader2 size={16} className="animate-spin"/>:gate?.eligible?'Request full rebuild':'Rebuild locked by audit'}</button></div></aside></div></section>}</div></main>;
}
