import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import AppShell from '../components/AppShell';
import { supabase } from '../lib/supabase';
import { formatError, getCurrentWorkspace } from '../lib/workspace';

const configs: Record<string,{title:string; eyebrow:string; description:string; table?:string; cta:string}> = {
  reviews:{title:'Review Intelligence',eyebrow:'REPUTATION ENGINE',description:'Turn customer feedback into recurring issues, strengths and prioritized operational actions.',table:'reviews',cta:'Analyze reviews'},
  marketing:{title:'Marketing Engine',eyebrow:'GROWTH CAMPAIGNS',description:'Build measurable campaigns around slow periods, offers, retention and local demand.',table:'marketing_campaigns',cta:'Create campaign'},
  social:{title:'Social Content',eyebrow:'CONTENT ENGINE',description:'Generate channel-ready content from your restaurant context, campaigns and growth priorities.',table:'social_content',cta:'Generate content'},
  reports:{title:'Growth Reports',eyebrow:'EXECUTIVE INTELLIGENCE',description:'Keep a persistent history of restaurant analyses, decisions and growth outcomes.',table:'reports',cta:'Create report'},
  billing:{title:'Billing',eyebrow:'SUBSCRIPTION',description:'Manage plan status, usage and the commercial layer of your GGA workspace.',table:'subscriptions',cta:'Billing settings'},
  integrations:{title:'Integrations',eyebrow:'CONNECTED DATA',description:'Connect the systems GGA needs to understand and execute restaurant growth workflows.',table:'integrations',cta:'Connect integration'},
};

export default function WorkspaceModulePage(){
 const {module='marketing'}=useParams(); const cfg=configs[module]??configs.marketing; const [rows,setRows]=useState<any[]>([]); const [restaurant,setRestaurant]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const ws=await getCurrentWorkspace();setRestaurant(ws.restaurant); if(!ws.restaurant)return; const query=supabase!.from(cfg.table!).select('*').eq(module==='billing'?'organization_id':'restaurant_id',module==='billing'?ws.membership.organization_id:ws.restaurant.id).order('created_at',{ascending:false}).limit(8); const {data,error}=await query;if(error)throw error;setRows(data??[]);}catch(e){setError(formatError(e));}finally{setLoading(false)}})()},[module,cfg.table]);
 const run = async()=>{if(module==='reviews'){setError('Add reviews first, then run Review Intelligence from the Reviews workspace.');return;} if(module==='marketing'){if(!restaurant)return; const {error}=await supabase!.from('marketing_campaigns').insert({restaurant_id:restaurant.id,name:'New GGA growth campaign',goal:'Increase qualified restaurant demand',status:'draft'});if(error)setError(error.message);else location.reload(); return;} if(module==='social'){if(!restaurant)return; const {error}=await supabase!.from('social_content').insert({restaurant_id:restaurant.id,platform:'instagram',content_type:'post',title:'GGA content draft',body:'Create a restaurant-specific social post from the latest growth priorities.',status:'draft'});if(error)setError(error.message);else location.reload();return;} setError('This module is ready for the next integration workflow.');};
 return <AppShell title={cfg.title}><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="text-xs font-medium tracking-[0.2em] text-violet-300/70">{cfg.eyebrow}</div><h2 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">{cfg.title}</h2><p className="mt-3 max-w-2xl text-zinc-400">{cfg.description}</p></div><button onClick={run} className="rounded-xl bg-violet-500 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-violet-500/10 hover:bg-violet-400">{cfg.cta}</button></div>
 <div className="grid gap-4 md:grid-cols-3"><Metric label="Workspace" value={restaurant?.name??'Not configured'} /><Metric label="Records" value={String(rows.length)} /><Metric label="System state" value={error?'Needs attention':'Operational'} /></div>
 {error&&<div className="mt-5 rounded-2xl border border-amber-400/20 bg-amber-400/5 p-4 text-sm text-amber-200">{error}</div>}
 <section className="mt-6 rounded-3xl border border-white/10 bg-white/[0.025] p-5 md:p-7"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-semibold">Recent activity</h3><p className="mt-1 text-sm text-zinc-500">Persistent workspace data, not demo cards.</p></div><Link to="/app/actions" className="text-sm text-violet-300">Action Center →</Link></div>{loading?<div className="py-12 text-center text-zinc-500">Loading workspace data...</div>:rows.length===0?<div className="rounded-2xl border border-dashed border-white/10 p-10 text-center"><div className="text-lg font-medium">No records yet</div><p className="mt-2 text-sm text-zinc-500">Use the module action above to create the first real workspace record.</p></div>:<div className="space-y-2">{rows.map((row)=> <div key={row.id} className="flex items-center justify-between rounded-2xl border border-white/5 bg-black/20 p-4"><div><div className="font-medium">{row.name??row.title??row.platform??row.plan_code??row.provider??'Record'}</div><div className="mt-1 text-xs text-zinc-500">{row.status??row.created_at}</div></div><span className="rounded-full bg-white/5 px-3 py-1 text-xs text-zinc-400">{row.status??'active'}</span></div>)}</div>}</section></AppShell>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><div className="text-xs uppercase tracking-wider text-zinc-500">{label}</div><div className="mt-2 truncate text-xl font-semibold">{value}</div></div>}
