import type { ReactNode } from 'react';
import { useState } from 'react';
import { Link, NavLink, useNavigate } from 'react-router-dom';
import { Activity, Bot, CreditCard, Globe2, LayoutDashboard, LogOut, Menu, PlugZap, Settings2, Sparkles, Target, UserRound, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

const nav = [
  ['Command Center', '/app/dashboard', LayoutDashboard], ['AI Advisor', '/app/advisor', Bot], ['Mission Control', '/app/missions', Target], ['Website Builder', '/app/website-builder', Globe2], ['Menu Intelligence', '/app/menu', Sparkles], ['Reviews', '/app/reviews', Activity], ['Marketing', '/app/marketing', Sparkles], ['Social Content', '/app/social', Sparkles], ['Actions', '/app/actions', Target], ['Reports', '/app/reports', Activity], ['Billing', '/app/billing', CreditCard], ['Integrations', '/app/integrations', PlugZap],
] as const;

export default function AppShell({ children, title }: { children: ReactNode; title?: string }) {
  const { signOut, user } = useAuth(); const navigate = useNavigate(); const [mobileOpen, setMobileOpen] = useState(false);
  const logout = async () => { await signOut(); navigate('/login'); }; const closeMobile = () => setMobileOpen(false);
  const navigation = (mobile = false) => <nav className={mobile ? 'space-y-1' : 'mt-6 space-y-1'} aria-label="GA workspace navigation">{nav.map(([label, path, Icon]) => <NavLink key={path} to={path} onClick={mobile ? closeMobile : undefined} className={({ isActive }) => `group relative flex items-center gap-3 overflow-hidden rounded-xl px-3 py-2.5 text-sm transition-all ${isActive ? 'bg-gradient-to-r from-violet-500/15 to-orange-400/10 text-white shadow-[inset_0_0_0_1px_rgba(255,255,255,.08)]' : 'text-zinc-500 hover:bg-white/[.045] hover:text-zinc-200'}`}><span className="absolute inset-y-1 left-0 w-0.5 rounded-full bg-gradient-to-b from-violet-400 to-orange-400 opacity-0 transition group-[.active]:opacity-100"/><Icon size={16} className="shrink-0 opacity-80"/><span>{label}</span></NavLink>)}</nav>;
  const brand = <Link to="/app/dashboard" onClick={closeMobile} className="group flex items-center gap-3 px-2 py-3"><span className="relative grid h-10 w-10 place-items-center overflow-hidden rounded-xl bg-gradient-to-br from-violet-500 via-fuchsia-500 to-orange-400 font-black text-white shadow-[0_8px_30px_rgba(139,92,246,.25)]"><span className="absolute inset-0 bg-white/10 opacity-0 transition group-hover:opacity-100"/>G</span><span><span className="block font-semibold tracking-tight text-white">GA</span><span className="block text-[9px] font-bold uppercase tracking-[.2em] text-zinc-600">Growth OS</span></span></Link>;

  return <div className="relative min-h-screen overflow-x-hidden bg-[#06070b] text-zinc-100"><div className="pointer-events-none fixed inset-0 -z-0 bg-[radial-gradient(circle_at_80%_0%,rgba(124,58,237,.12),transparent_28%),radial-gradient(circle_at_45%_100%,rgba(249,115,22,.07),transparent_26%)]"/>
    <aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-white/[.07] bg-[#07080c]/90 p-4 backdrop-blur-2xl lg:block">{brand}{navigation()}<div className="absolute bottom-4 left-4 right-4 border-t border-white/[.07] pt-4"><div className="flex items-center gap-2 px-2 text-xs text-zinc-500"><UserRound size={13}/><span className="truncate">{user?.email}</span></div><button onClick={logout} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-white/[.08] px-3 py-2 text-sm text-zinc-400 transition hover:border-white/15 hover:bg-white/[.04] hover:text-white"><LogOut size={14}/>Sign out</button></div></aside>
    {mobileOpen && <div className="fixed inset-0 z-40 lg:hidden" role="dialog" aria-modal="true" aria-label="GA navigation"><button aria-label="Close navigation" className="absolute inset-0 bg-black/75 backdrop-blur-sm" onClick={closeMobile}/><aside className="absolute inset-y-0 left-0 w-[min(20rem,88vw)] border-r border-white/[.08] bg-[#08090e] p-4 shadow-2xl">{brand}<button aria-label="Close navigation" onClick={closeMobile} className="absolute right-4 top-5 rounded-lg p-2 text-zinc-400 hover:bg-white/5 hover:text-white"><X size={18}/></button><div className="mt-4">{navigation(true)}</div><div className="mt-6 border-t border-white/[.07] pt-4"><div className="truncate px-3 text-xs text-zinc-500">{user?.email}</div><button onClick={logout} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-white/[.08] px-3 py-2 text-sm text-zinc-400"><LogOut size={14}/>Sign out</button></div></aside></div>}
    <main className="relative z-10 min-h-screen lg:pl-64"><header className="sticky top-0 z-20 border-b border-white/[.07] bg-[#06070b]/80 px-4 py-3 backdrop-blur-2xl md:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><button aria-label="Open navigation" onClick={() => setMobileOpen(true)} className="rounded-xl border border-white/[.08] p-2 text-zinc-300 hover:bg-white/5 lg:hidden"><Menu size={18}/></button><div className="min-w-0"><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.24em] text-violet-300/70"><Settings2 size={11}/> GA / Business Growth Operating System</div>{title && <h1 className="mt-1 truncate text-lg font-semibold tracking-tight text-white md:text-xl">{title}</h1>}</div></div><div className="flex items-center gap-2"><Link to="/app/missions" className="hidden rounded-xl border border-white/[.08] px-3 py-2 text-xs font-semibold text-zinc-300 transition hover:border-violet-400/20 hover:bg-white/[.04] sm:inline-flex">Mission Control</Link><Link to="/app/website-builder" className="hidden rounded-xl bg-gradient-to-r from-violet-400 to-orange-300 px-4 py-2 text-sm font-bold text-black shadow-[0_8px_25px_rgba(139,92,246,.16)] transition hover:-translate-y-0.5 sm:inline-flex">Build website</Link></div></div></header><div className="mx-auto max-w-7xl p-4 md:p-8">{children}</div></main>
  </div>;
}
