import { Link } from "react-router-dom";
import { ArrowUpRight, Bot, BrainCircuit, Gauge, ShieldCheck, Sparkles, Target, Zap } from "lucide-react";

type Mission = { id: string; title: string; goal: string; priority: number; status: string; approval_status: string; target_value: number | null; baseline_value: number | null; unit: string | null; created_at: string };
type Action = { id: string; mission_id: string; title: string; description: string | null; status: string; impact_score: number; effort_score: number; risk_level: string; due_at: string | null };
type Measurement = { id: string; mission_id: string; kpi: string; before_value: number | null; after_value: number | null; delta: number | null; confidence: number; measured_at: string };
type Learning = { id: string; kpi: string; recommendation: string; confidence: number; sample_size: number; created_at: string };
type Props = { score?: number | null; rating?: number | null; reviews?: number | null; restaurantName?: string | null; missions?: Mission[]; actions?: Action[]; measurements?: Measurement[]; learning?: Learning[]; onApprove?: (missionId: string) => Promise<void> };

export default function GrowthCommandCenter({ score, rating, reviews, restaurantName, missions = [], actions = [], measurements = [], learning = [], onApprove }: Props) {
  const health = typeof score === "number" ? Math.max(0, Math.min(100, Math.round(score))) : null;
  const activeMission = missions.find((m) => ["active", "executing", "measuring"].includes(m.status) || m.approval_status === "pending") ?? missions[0];
  const pendingApproval = missions.filter((m) => m.approval_status === "pending").length;
  const activeActions = actions.filter((a) => ["approved", "in_progress", "executing"].includes(a.status)).length;
  const completedMeasurements = measurements.filter((m) => m.after_value !== null).length;
  const lastLearning = learning[0];
  const priority = health !== null && health < 50 ? "CRITICAL" : health !== null && health < 70 ? "HIGH" : "OPTIMIZE";
  const status = pendingApproval > 0 ? "Approval required" : activeMission ? "Agent loop active" : "Ready for diagnosis";

  return <section className="relative overflow-hidden rounded-[28px] border border-white/10 bg-slate-950 p-4 text-white shadow-2xl sm:p-7">
    <div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-purple-600/20 blur-3xl" /><div className="pointer-events-none absolute -bottom-32 left-1/3 h-72 w-72 rounded-full bg-cyan-500/10 blur-3xl" />
    <div className="relative flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-purple-400/20 bg-purple-500/10 px-3 py-1 text-[11px] font-semibold text-purple-200"><Sparkles size={13}/> GGA INTELLIGENCE</div><h2 className="text-2xl font-black tracking-tight sm:text-3xl">Growth Command Center</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">{restaurantName ? `${restaurantName} is connected to the autonomous growth loop.` : "Your AI growth system monitors signals, prioritizes opportunities and measures outcomes."}</p></div><div className={`inline-flex w-fit items-center gap-2 rounded-2xl border px-4 py-3 text-sm ${pendingApproval ? "border-amber-400/20 bg-amber-400/5 text-amber-300" : "border-emerald-400/20 bg-emerald-400/5 text-emerald-300"}`}><span className={`h-2 w-2 animate-pulse rounded-full ${pendingApproval ? "bg-amber-400" : "bg-emerald-400"}`}/>{status}</div></div>
    <div className="relative mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Growth Health",health===null?"--":health+"/100",Gauge],["Active Actions",String(activeActions),Zap],["Measured",String(completedMeasurements),Target],["Learning",lastLearning?Math.round(lastLearning.confidence*100)+"%":"--",BrainCircuit]].map(([label,value,Icon])=><div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.035] p-4 sm:p-5"><div className="flex items-center justify-between text-slate-500"><span className="text-[10px] font-semibold uppercase tracking-wider">{label}</span><Icon size={16}/></div><div className="mt-3 text-2xl font-black text-white">{value}</div>{label==="Growth Health"&&health!==null&&<div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-violet-400 to-cyan-300" style={{width:`${health}%`}}/></div>}</div>)}</div>
    <div className="relative mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
      <div className="rounded-2xl border border-white/10 bg-white/[.035] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-widest text-purple-300">LIVE MISSION</p><h3 className="mt-2 text-xl font-bold">{activeMission?.title || (health===null?"Run your first growth diagnosis":"Next growth mission")}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{activeMission?.goal || "GGA converts business signals into a bounded, measurable growth mission."}</p></div><div className="rounded-xl bg-purple-500/10 p-3 text-purple-300"><Bot size={22}/></div></div>
        {activeMission&&<div className="mt-5 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-black/20 p-3"><p className="text-[10px] uppercase text-slate-500">Priority</p><p className="mt-1 font-bold text-white">{activeMission.priority}</p></div><div className="rounded-xl bg-black/20 p-3"><p className="text-[10px] uppercase text-slate-500">Approval</p><p className="mt-1 font-bold text-white">{activeMission.approval_status}</p></div><div className="rounded-xl bg-black/20 p-3"><p className="text-[10px] uppercase text-slate-500">Actions</p><p className="mt-1 font-bold text-white">{actions.filter(a=>a.mission_id===activeMission.id).length}</p></div></div>}
        {activeMission&&activeMission.approval_status==="pending"&&onApprove&&<button onClick={()=>void onApprove(activeMission.id)} className="mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-slate-950 transition hover:-translate-y-0.5 active:translate-y-0"><ShieldCheck size={16}/> Approve mission</button>}{!activeMission&&<Link to="/app/advisor" className="mt-5 inline-flex min-h-12 items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-slate-950">Run GGA Advisor <ArrowUpRight size={16}/></Link>}
      </div>
      <div className="rounded-2xl border border-white/10 bg-white/[.035] p-5 sm:p-6"><p className="text-[11px] font-bold uppercase tracking-widest text-slate-500">AUTONOMOUS LOOP</p><div className="mt-4 space-y-2">{[["Diagnosis","done"],["Mission",activeMission?"live":"waiting"],["Approval",pendingApproval?"pending":"clear"],["Execution",activeActions?"live":"waiting"],["Measurement",completedMeasurements?"live":"waiting"],["Learning",lastLearning?"learned":"waiting"]].map(([title,state],i)=><div key={title} className="flex items-center gap-3 rounded-xl border border-white/5 bg-black/15 px-3 py-2.5"><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${state==="pending"?"bg-amber-400":state==="live"?"bg-purple-400 shadow-[0_0_12px_rgba(168,85,247,.7)]":state==="learned"||state==="done"?"bg-emerald-400":"bg-slate-700"}`}/><span className="flex-1 text-sm text-slate-200">{i+1}. {title}</span><span className="text-[10px] uppercase text-slate-500">{state}</span></div>)}</div><p className="mt-4 border-t border-white/[.06] pt-4 text-xs leading-5 text-slate-600">AI proposes. Policy checks. You approve. GGA executes, measures and learns.</p></div>
    </div>
    <div className="relative mt-5 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span className="rounded-full border border-white/10 px-3 py-1.5">Priority: {priority}</span><span className="rounded-full border border-white/10 px-3 py-1.5">Reviews: {reviews?.toLocaleString() ?? "--"}</span><span className="rounded-full border border-white/10 px-3 py-1.5">Rating: {rating?.toFixed(1) ?? "--"}/5</span><span className="rounded-full border border-white/10 px-3 py-1.5">{missions.length} missions</span></div>
  </section>;
}
