import React from "react";
import { Navigate, Route, Routes } from "react-router-dom";
import { LanguageProvider } from "./context/LanguageContext";
import Header from "./components/Header";
import Hero from "./sections/Hero";
import Problem from "./sections/Problem";
import Process from "./sections/Process";
import WhatWeBuild from "./sections/WhatWeBuild";
import AIMenuScanner from "./sections/AIMenuScanner";
import HealthScore from "./sections/HealthScore";
import DashboardPreview from "./sections/DashboardPreview";
import Testimonials from "./sections/Testimonials";
import MultiStepForm from "./sections/MultiStepForm";
import WhyUs from "./sections/WhyUs";
import CaseStudies from "./sections/CaseStudies";
import Pricing from "./sections/Pricing";
import CompetitorAnalysis from "./sections/CompetitorAnalysis";
import ReviewIntelligence from "./sections/ReviewIntelligence";
import FAQ from "./sections/FAQ";
import AdvancedAnalytics from "./sections/AdvancedAnalytics";
import GrowthRoadmap from "./sections/GrowthRoadmap";
import FinalCTAEnhanced from "./sections/FinalCTAEnhanced";
import SocialProof from "./sections/SocialProof";
import NewsletterSignup from "./sections/NewsletterSignup";
import FooterLinks from "./sections/FooterLinks";
import Footer from "./components/Footer";
import PricingCalculator from "./sections/PricingCalculator";
import IntegrationLogos from "./sections/IntegrationLogos";
import BlogPreview from "./sections/BlogPreview";
import AIBlogGenerator from "./sections/AIBlogGenerator";
import SEOChecker from "./sections/SEOChecker";
import LoadingState from "./sections/LoadingState";
import ErrorBoundary from "./sections/ErrorBoundary";
import DarkMode from "./sections/DarkMode";
import CustomerJourney from "./sections/CustomerJourney";
import AutomationRules from "./sections/AutomationRules";
import APIIntegration from "./sections/APIIntegration";
import TeamMembers from "./sections/TeamMembers";
import OnboardingWizard from "./sections/OnboardingWizard";
import AuthPage from "./pages/AuthPage";
import DashboardPage from "./pages/DashboardPage";
import OnboardingPage from "./pages/OnboardingPage";
import AdvisorPage from "./pages/AdvisorPage";
import MenuPage from "./pages/MenuPage";
import ActionsPage from "./pages/ActionsPage";
import WorkspaceModulePage from "./pages/WorkspaceModulePage";

function PublicSite() { return <LanguageProvider><div className="relative min-h-screen bg-background text-foreground overflow-x-hidden"><Header/><main><Hero/><Problem/><Process/><WhatWeBuild/><AIMenuScanner/><HealthScore/><DashboardPreview/><Testimonials/><MultiStepForm/><WhyUs/><CaseStudies/><Pricing/><CompetitorAnalysis/><ReviewIntelligence/><FAQ/><AdvancedAnalytics/><GrowthRoadmap/><FinalCTAEnhanced/><SocialProof/><NewsletterSignup/><FooterLinks/><PricingCalculator/><IntegrationLogos/><BlogPreview/><AIBlogGenerator/><SEOChecker/><LoadingState/><ErrorBoundary/><DarkMode/><CustomerJourney/><AutomationRules/><APIIntegration/><TeamMembers/><OnboardingWizard/></main><Footer/></div></LanguageProvider>; }

export default function App() { return <Routes><Route path="/" element={<PublicSite/>}/><Route path="/login" element={<AuthPage/>}/><Route path="/signup" element={<AuthPage/>}/><Route path="/app/onboarding" element={<OnboardingPage/>}/><Route path="/app/dashboard" element={<DashboardPage/>}/><Route path="/app/advisor" element={<AdvisorPage/>}/><Route path="/app/menu" element={<MenuPage/>}/><Route path="/app/actions" element={<ActionsPage/>}/><Route path="/app/:module" element={<WorkspaceModulePage/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>; }
